# Generated by Django 5.0 on 2026-02-13 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for this booking', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 13, 32, 21, 427579, tzinfo=datetime.timezone.utc), help_text='The scheduled date/time for the session'),
            preserve_default=False,
        ),
    ]
