# Generated by Django 5.2.11 on 2026-02-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_catalog', '0002_alter_session_options_alter_session_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_cat_status_b9458a_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='session_cat_creator_2cd967_idx',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='session',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='session',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Maximum number of participants'),
        ),
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
