# Generated by Django 5.0 on 2026-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_catalog', '0003_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_bookings',
            field=models.IntegerField(default=0, help_text='Current number of bookings'),
        ),
    ]
