# Generated by Django 5.0 on 2026-02-13 17:01

import session_catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_catalog', '0004_session_current_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=session_catalog.models.session_image_path),
        ),
    ]
