# Generated by Django 5.0 on 2026-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_catalog', '0005_alter_session_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image_url_external',
            field=models.URLField(blank=True, help_text='External image URL (alternative to upload)', null=True),
        ),
    ]
