# Generated by Django 5.0 on 2026-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_catalog', '0006_session_image_url_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image_url_external',
            field=models.URLField(blank=True, help_text='External image URL (alternative to upload)', max_length=2000, null=True),
        ),
    ]
